spring:
  application:
    name: openpayd

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:forexdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  profiles:
    active: dev

external-api:
  url: https://data.fixer.io/api/latest
  api-key: 0a5f28039a528338c606d27c78c40e3b

logging:
  level:
    org:
      springdoc: DEBUG
      springframework.web: DEBUG
